### ISSUE TITLE
New buy drawer design and functionality. 

### ISSUE THREAD

**Issue by zooqueen** [luxfi/web#120]
<img width="514" alt="Screenshot 2024-03-26 at 4 02 12 PM" src="https://github.com/luxfi/web/assets/98129351/fb1a0984-edb3-4f4a-a061-2f3c1f843748">

SVG: ![shoppingbag](https://github.com/luxfi/web/assets/98129351/a24487a1-069b-4336-a827-5f212a768860)

**Comment by zooqueen** [comment]
![shoppingbag](https://github.com/luxfi/web/assets/98129351/8fbad73d-9425-4c9d-ad72-274956dd9bb9)

**Comment by artemis-prime** [comment]
Please clarify the intended change.  Are you asking to add the bag icon to the button, or to change the icon itself where it currently is or ?  Please be stupidly clear :) @zooqueen

**Comment by zeekay** [comment]
Please use this icon everywhere for now.

**Comment by zeekay** [comment]
![image](https://github.com/luxfi/web/assets/285707/c79e1f4b-773c-4dff-bf56-b57133e61491)

**Comment by artemis-prime** [comment]
@zeekay , what happens when the drawer closes? Do we still want a floating checkout button next to the AI Chat button?

**Comment by artemis-prime** [comment]
> I think rather than + you can show shopping bag on the add to bag button, and then show checkout once something is added.

So to clarify:
none in bag:  "add <bag icon>"
1 or more in bag: Button is same as current "- (or trash icon) n +", AND checkout button appears below

Correct?

**Comment by artemis-prime** [comment]
Also, to confirm the carousel / indicator / variant picker design and logic.  We have 3 cases.

1) If no groupings or variants (Pass):
  Item media, title, (byline), and price
  
2) no variant groupings (Coin, Validator):
 * carousel slide is variant: Item media, title, (byline), and price
 * progress slider roughly indicates variant "size" and allows sliding through quickly
 
3) variant groups (Credit, AU, AG):
 * carousel slide is ** grouping ** ("level" for credit, and "bullion form" for AU and AG)
 * slide contains a picker for variant:  round swatches for Credit, and vertical button list for AU and AG (up to 5)
 (imho: since there are at most 4 slides, I think the progress indicator isn't so necessary and doesn't add much since it's not about "amount" or "cost" or "size" the way it is in the previous case)
 
Correct?

**Comment by artemis-prime** [comment]
completed a PRs #156 , and #176
