### ISSUE TITLE
UI: Update logo, chat icon, font sizes

### ISSUE THREAD

**Issue by zeekay** [luxfi/web#162]
Make the logo just LUX top left, remove triangle, and on the AI chat,  remove the circle. 

Make it just a floating white triangle and when you hover can you make it subtly glow with CSS (one approach: https://codepen.io/Ks145/pen/MWGxbYr, white color tho obv). 

LUX should be 1.8rem quite a bit bigger than before, triangle size is fine, just get rid of the bg and white outline.

For nav and buttons make font 1rem by default also after switching from Druk missing some punch.

**Comment by erikrakuscek** [comment]
Additional requirements:

- font weight for buttons should be 600

- no white border on buttons (grey circle bg on hover is ok, but should have transparent bg to be less obtrusive otherwise.
![WhatsApp Image 2024-04-11 at 19 26 02_13d486f3](https://github.com/luxfi/web/assets/17453589/a9d0d040-167b-4bdd-81c2-19eea0e790a4)

- On checkout let’s bring back LUX rather than triangle in top left.

- Make bread crumbs on checkout Bag > Payment > Delivery > Confirm. Bag should go back from checkout to previous page with Shopping Bag open on right
![WhatsApp Image 2024-04-11 at 19 26 30_3477937b](https://github.com/luxfi/web/assets/17453589/d21dc960-4896-46ca-9b08-0cfbf9bca237)

- Rather than x, flip the triangle upside down when chat is open
![WhatsApp Image 2024-04-11 at 19 27 35_72472b4e](https://github.com/luxfi/web/assets/17453589/a79811b1-e3eb-42ac-80bf-d6e878f90760)

- In this view could use triangle as minimise icon
![WhatsApp Image 2024-04-11 at 19 28 06_5b6ea611](https://github.com/luxfi/web/assets/17453589/9453eeaa-f89f-4781-9c80-845f76e2d4e5)

- Update lux.credit landing page
![WhatsApp Image 2024-04-11 at 19 55 31_a8f4c51b](https://github.com/luxfi/web/assets/17453589/7c02fc0d-de8d-48c0-8400-91a23fe44f4c)
