### ISSUE TITLE
network: Landing page

### ISSUE THREAD

**Issue by zooqueen** [luxfi/web#231]
At the bottom of the page for lux.network 

-Replace the gold bar with the lux key video
-turn on silver animation video so it is playing
-synchronize the speed of all the animations 

<img width="1340" alt="Untitled 2" src="https://github.com/luxfi/web/assets/98129351/e0d4c7d8-97a5-45f6-addd-c97d3591da82">

**Comment by artemis-prime** [comment]
- [ ] Replace the gold bar with the lux key video
- [ ] turn on silver animation video so it is playing
- [ ] synchronize the speed of all the animations

**Comment by artemis-prime** [comment]
Silver animation always plays for me

Sync is not possible.  There is no way to control that since they are all shot at diff speeds and have diff loop lengths.  Even if that was not the case, there is no notion of "synchronizing" videos (outside of a very high end solution that would be way more money and 
trouble than we can likely afford)
